"""
Abstract base class for all trading strategies.

Each strategy must be able to:
1. Generate entry signals
2. Compute SL/TP levels
3. Produce a complete trade proposal
4. Operate independently for LONG vs SHORT

Strategies are stateless — they operate on DataFrames and return signals.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, List, Literal, Optional, Tuple

import numpy as np
import pandas as pd

from utils.logger import get_logger

log = get_logger(__name__)

Side = Literal["long", "short"]


@dataclass
class TradeProposal:
    """
    A single trade proposal generated by a strategy.
    Passed to risk engine and then to signal engine.
    """
    timestamp: pd.Timestamp
    asset: str
    strategy: str
    regime: str
    side: Side
    entry: float
    stop_loss: float
    take_profit: float
    confidence: float = 0.5
    signal_strength: float = 0.5   # 0–1 internal strength metric
    params: Dict = field(default_factory=dict)
    notes: str = ""

    @property
    def risk_pips(self) -> float:
        if self.side == "long":
            return self.entry - self.stop_loss
        return self.stop_loss - self.entry

    @property
    def reward_pips(self) -> float:
        if self.side == "long":
            return self.take_profit - self.entry
        return self.entry - self.take_profit

    @property
    def rr_ratio(self) -> float:
        if self.risk_pips <= 0:
            return 0.0
        return self.reward_pips / self.risk_pips

    def is_valid(self) -> bool:
        """Check all numeric fields are finite, positive, and SL/TP make sense."""
        nums = [self.entry, self.stop_loss, self.take_profit,
                self.confidence, self.signal_strength]
        if any(np.isnan(v) or np.isinf(v) for v in nums):
            return False
        return (
            self.entry > 0 and
            self.stop_loss > 0 and
            self.take_profit > 0 and
            self.risk_pips > 0 and
            self.rr_ratio >= 0.5
        )

    def to_dict(self) -> dict:
        return {
            "timestamp":       self.timestamp.isoformat(),
            "asset":           self.asset,
            "strategy":        self.strategy,
            "regime":          self.regime,
            "side":            self.side,
            "entry":           round(self.entry, 6),
            "stop_loss":       round(self.stop_loss, 6),
            "take_profit":     round(self.take_profit, 6),
            "rr_ratio":        round(self.rr_ratio, 2),
            "confidence":      round(self.confidence, 4),
            "signal_strength": round(self.signal_strength, 4),
            "notes":           self.notes,
        }


class BaseStrategy(ABC):
    """
    Abstract base for all strategies.

    Strategies receive a fully-featured DataFrame (OHLCV + features)
    and return entry signals or TradeProposal objects.
    """

    name: str = "base"
    suitable_regimes: List[str] = []

    def __init__(
        self,
        params_long: Optional[Dict] = None,
        params_short: Optional[Dict] = None,
    ):
        self.params_long  = {**self.default_params(), **(params_long or {})}
        self.params_short = {**self.default_params(), **(params_short or {})}

    @abstractmethod
    def default_params(self) -> Dict:
        """Return default parameter dict for this strategy."""
        ...

    @abstractmethod
    def generate_signals(
        self,
        df: pd.DataFrame,
        side: Side = "long",
        asset: str = "",
        regime: str = "",
    ) -> pd.DataFrame:
        """
        Compute entry signals on the full DataFrame.

        Returns df with added columns:
            signal:  +1 (long entry), -1 (short entry), 0 (no signal)
            sl:      stop-loss price for the bar
            tp:      take-profit price for the bar
            strength: signal strength [0, 1]
        """
        ...

    def get_latest_proposal(
        self,
        df: pd.DataFrame,
        side: Side,
        asset: str,
        regime: str,
        regime_confidence: float = 0.5,
        lookback_bars: int = 8,
    ) -> Optional[TradeProposal]:
        """
        Check the most recent bars for a signal and return a TradeProposal.
        Returns None if no signal in the last `lookback_bars` bars or values are invalid.

        In live mode the loop polls every 5 minutes but uses 1H bars, so a signal
        on bar N may be missed if we only check the very last bar (N+1 may have
        no signal). Scanning back a few bars prevents missed entries.
        """
        signals = self.generate_signals(df, side=side, asset=asset, regime=regime)
        if signals.empty:
            return None

        expected_signal = 1 if side == "long" else -1

        # Scan last N bars for a signal (most recent first)
        last = None
        for i in range(1, min(lookback_bars + 1, len(signals) + 1)):
            candidate = signals.iloc[-i]
            if candidate.get("signal", 0) == expected_signal:
                last = candidate
                break

        if last is None:
            return None

        # Reject stale signals where price has moved too far from the signal bar
        # In the backtest, entry is at the signal bar close. In live mode, if price
        # has already moved >1.5R against or >2R in favor, the setup is no longer
        # aligned with what was backtested.
        current_price = float(signals.iloc[-1]["close"])
        signal_entry = float(last["close"])
        signal_sl = float(last.get("sl", 0))
        if signal_sl > 0 and signal_entry > 0:
            sl_dist = abs(signal_entry - signal_sl)
            if sl_dist > 0:
                price_move = current_price - signal_entry
                if side == "short":
                    price_move = -price_move
                move_r = price_move / sl_dist
                if move_r < -1.5:
                    log.info(
                        "%s/%s: rejecting stale signal — price moved %.1fR against entry",
                        asset, self.name, move_r,
                    )
                    return None
                if move_r > 2.0:
                    log.info(
                        "%s/%s: rejecting stale signal — price moved %.1fR past entry (chasing)",
                        asset, self.name, move_r,
                    )
                    return None

        # Extract and validate numeric values — reject NaN/inf/zero
        entry    = float(last["close"])
        sl_val   = float(last.get("sl", 0))
        tp_val   = float(last.get("tp", 0))
        strength = float(last.get("strength", 0.5))

        for name, val in [("entry", entry), ("sl", sl_val), ("tp", tp_val)]:
            if val <= 0 or np.isnan(val) or np.isinf(val):
                log.debug(
                    "%s/%s: rejecting signal — invalid %s=%.6f",
                    asset, self.name, name, val,
                )
                return None

        # Clamp strength to [0, 1] and replace NaN
        if np.isnan(strength) or np.isinf(strength):
            strength = 0.5
        strength = max(0.0, min(1.0, strength))

        proposal = TradeProposal(
            timestamp       = last.name if hasattr(last, 'name') else signals.index[-1],
            asset           = asset,
            strategy        = self.name,
            regime          = regime,
            side            = side,
            entry           = entry,
            stop_loss       = sl_val,
            take_profit     = tp_val,
            confidence      = float(regime_confidence),
            signal_strength = strength,
            params          = self.params_long if side == "long" else self.params_short,
            notes           = last.get("notes", ""),
        )

        if not proposal.is_valid():
            log.debug(
                "%s/%s: proposal failed validation (RR=%.2f)",
                asset, self.name, proposal.rr_ratio,
            )
            return None

        return proposal

    def set_params(self, params: Dict, side: Side = "long") -> "BaseStrategy":
        if side == "long":
            self.params_long = {**self.default_params(), **params}
        else:
            self.params_short = {**self.default_params(), **params}
        return self

    def get_params(self, side: Side = "long") -> Dict:
        return self.params_long if side == "long" else self.params_short

    @property
    def param_schema(self) -> Dict:
        """Return parameter schema for optimization search space."""
        return {}

    @staticmethod
    def _sanitize_signals(out: pd.DataFrame) -> pd.DataFrame:
        """
        Clean NaN/inf from signal output columns.
        Rows with NaN in sl/tp have their signal zeroed out.
        """
        for col in ("sl", "tp", "strength"):
            if col in out.columns:
                out[col] = out[col].replace([np.inf, -np.inf], np.nan)
        # Zero out signal where sl or tp is NaN (can't trade without levels)
        bad_mask = out["sl"].isna() | out["tp"].isna()
        if bad_mask.any():
            out.loc[bad_mask, "signal"] = 0
        # Fill remaining NaN strength with 0
        if "strength" in out.columns:
            out["strength"] = out["strength"].fillna(0).clip(0, 1)
        return out

    def _atr(self, df: pd.DataFrame, period: int = 14) -> pd.Series:
        """Compute ATR if not already in df."""
        if "atr" in df.columns:
            return df["atr"]
        tr = pd.concat([
            df["high"] - df["low"],
            (df["high"] - df["close"].shift(1)).abs(),
            (df["low"]  - df["close"].shift(1)).abs(),
        ], axis=1).max(axis=1)
        return tr.ewm(span=period, adjust=False).mean()
